### ISSUE TITLE
Doubt on logentries API

### ISSUE THREAD

**Issue by vhaberkorn** [pagarme/logentries-bot#17]
Hey @julianaklulo , @vagnervst and @murilohns 
I have one doubt regarding the logentries API that I couldn't find on the docs. Since you guys played with that to build the bot, I hope that you can help me.
Can I iterate through logs using logset_id and log_id?
I want to get logs using the log_id inside some logsets.

**Comment by julianaklulo** [comment]
Hello!
I had a similar doubt and asked the logentries support, and they said that you can get the log_ids from a logset using the logset_id, but you can't use the logset_id anywhere (except to get the log_ids inside the logset). If you need to access all the logs in a logset, you need to create a list with those log_ids, if you use the logset_id it won't work.
Hope that helps!

**Comment by vhaberkorn** [comment]
That's already helping, @julianaklulo.
But the thing is I already have the list of log_ids and i need to interact with them using the logentries API but the methods only let you interact with log file and not a log line.

**Comment by julianaklulo** [comment]
Now I got what you're saying. Have you tried using the Live Tail API? You can get the log lines, but only as they arrive. If you need specific lines that already are in the log file, I don't think I can help with that ):

**Comment by vhaberkorn** [comment]
Tail the log is not an option.
I need to access specific lines.

Thank you very much for the help, @julianaklulo !
